# SPDX-License-Identifier: Apache-2.0
# Copyright 2026 Firelock, LLC
#
# GENERATED by scripts/render-formula.sh. Do not hand-edit. The version and
# sha256s are regenerated from each kin release by
# .github/workflows/update-formula.yml, so they can never drift from the
# published assets.
class Kin < Formula
  desc "A graph-native code repository for people and AI agents."
  homepage "https://github.com/firelock-ai/kin"
  version "0.7.12"
  license "Apache-2.0"

  on_macos do
    on_arm do
      url "https://github.com/firelock-ai/kin/releases/download/v#{version}/kin-macos-aarch64.tar.gz"
      sha256 "939ef7dfaea39d813f8e4890a157d43792072a3b4a12b72cf6c072d37301a153"
    end
    on_intel do
      url "https://github.com/firelock-ai/kin/releases/download/v#{version}/kin-macos-x86_64.tar.gz"
      sha256 "2ccfb6d5a73196712f2bdc99919be33241066bd95c55c0b7386df53fc4d004c7"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/firelock-ai/kin/releases/download/v#{version}/kin-linux-x86_64.tar.gz"
      sha256 "622338979155dd48de4dfb5920c22889e62b9e98548dbe69425369a6a00ed88c"
    end
    on_arm do
      url "https://github.com/firelock-ai/kin/releases/download/v#{version}/kin-linux-aarch64.tar.gz"
      sha256 "1b511e4b5d3111c3f6ed5d3bb004d1d37acd7f045a7d5aaf4acd3eb9816a554f"
    end
  end

  def install
    # The release tarball expands to a single dir (e.g. kin-macos-aarch64/)
    # holding kin, kin-daemon, kin-vfs, and the VFS shim. Homebrew cd's into
    # that root on extract. kin-daemon is mandatory: kin init works without it,
    # but kin status / kin search / the MCP server all require it on PATH.
    bin.install "kin"
    bin.install "kin-daemon"
    bin.install "kin-vfs" if File.exist?("kin-vfs")
    lib.install "libkin_vfs_shim.dylib" if File.exist?("libkin_vfs_shim.dylib")
    lib.install "libkin_vfs_shim.so" if File.exist?("libkin_vfs_shim.so")
  end

  test do
    assert_match "kin", shell_output("#{bin}/kin --version")
  end
end
