# SPDX-License-Identifier: Apache-2.0
# Copyright 2026 Firelock, LLC
#
# GENERATED by scripts/render-formula.sh. Do not hand-edit. The version and
# sha256s are regenerated from each kin release by
# .github/workflows/update-formula.yml, so they can never drift from the
# published assets.
class Kin < Formula
  desc "Semantic system of record for AI-written software"
  homepage "https://github.com/firelock-ai/kin"
  version "0.5.29"
  license "Apache-2.0"

  on_macos do
    on_arm do
      url "https://github.com/firelock-ai/kin/releases/download/v#{version}/kin-macos-aarch64.tar.gz"
      sha256 "8aecfa660fed027c7b1ed0c60230a8727992caa8249b89cbed38e71fb7915f7f"
    end
    on_intel do
      url "https://github.com/firelock-ai/kin/releases/download/v#{version}/kin-macos-x86_64.tar.gz"
      sha256 "0e8e0985780058feaf088de2c9686e913e436b74704bebb891fdece2de1e14d1"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/firelock-ai/kin/releases/download/v#{version}/kin-linux-x86_64.tar.gz"
      sha256 "b911144c83cc3d9ec1644832de37028326f6c4ba1d501e66ada901151bffd49c"
    end
    on_arm do
      url "https://github.com/firelock-ai/kin/releases/download/v#{version}/kin-linux-aarch64.tar.gz"
      sha256 "e4357f88997f2af85704fa9094502c0f86c6c517fc67b01faa42181fb66789c5"
    end
  end

  def install
    # The release tarball expands to a single dir (e.g. kin-macos-aarch64/)
    # holding kin, kin-daemon, kin-vfs, and the VFS shim. Homebrew cd's into
    # that root on extract. kin-daemon is mandatory: kin init works without it,
    # but kin status / kin search / the MCP server all require it on PATH.
    bin.install "kin"
    bin.install "kin-daemon"
    bin.install "kin-vfs" if File.exist?("kin-vfs")
    lib.install "libkin_vfs_shim.dylib" if File.exist?("libkin_vfs_shim.dylib")
    lib.install "libkin_vfs_shim.so" if File.exist?("libkin_vfs_shim.so")
  end

  test do
    assert_match "kin", shell_output("#{bin}/kin --version")
  end
end
