# SPDX-License-Identifier: Apache-2.0
# Copyright 2026 Firelock, LLC
#
# GENERATED by scripts/render-formula.sh — do not hand-edit. The version and
# sha256s are regenerated from each kin release by
# .github/workflows/update-formula.yml, so they can never drift from the
# published assets.
class Kin < Formula
  desc "Semantic system of record for software work"
  homepage "https://github.com/firelock-ai/kin"
  version "0.2.7"
  license "Apache-2.0"

  on_macos do
    on_arm do
      url "https://github.com/firelock-ai/kin/releases/download/v#{version}/kin-macos-aarch64.tar.gz"
      sha256 "a87554f762e52a36e7959273ac398a832dfe5024e336eb8ab7b1734bdddea3fe"
    end
    on_intel do
      url "https://github.com/firelock-ai/kin/releases/download/v#{version}/kin-macos-x86_64.tar.gz"
      sha256 "d9d079affbe16e316629da28b49866423c99fcd0dc97c84aeff5b29466cc1add"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/firelock-ai/kin/releases/download/v#{version}/kin-linux-x86_64.tar.gz"
      sha256 "81fad444980a428501ec5a856a8728fd4c42de0fd8656106c01d5e8ec3ccaa63"
    end
    on_arm do
      url "https://github.com/firelock-ai/kin/releases/download/v#{version}/kin-linux-aarch64.tar.gz"
      sha256 "107ec65a3397d4242e164a3218c298b7926fb258fd5a21bd248726ab6515e717"
    end
  end

  def install
    # The release tarball expands to a single dir (e.g. kin-macos-aarch64/)
    # holding kin, kin-daemon, kin-vfs, and the VFS shim. Homebrew cd's into
    # that root on extract. kin-daemon is mandatory: kin init works without it,
    # but kin status / kin search / the MCP server all require it on PATH.
    bin.install "kin"
    bin.install "kin-daemon"
    bin.install "kin-vfs" if File.exist?("kin-vfs")
    lib.install "libkin_vfs_shim.dylib" if File.exist?("libkin_vfs_shim.dylib")
    lib.install "libkin_vfs_shim.so" if File.exist?("libkin_vfs_shim.so")
  end

  test do
    assert_match "kin", shell_output("#{bin}/kin --version")
  end
end
