#!/usr/bin/env bash
# Render Formula/kin.rb from a kin release. This is the single source of truth
# for the tap: the formula is a GENERATED artifact, never hand-edited, so its
# sha256s can never drift from the published release assets (the failure mode
# that silently broke the previous in-repo formula).
#
# Usage:
#   scripts/render-formula.sh <version> <sha_macos_arm> <sha_macos_intel> <sha_linux_intel> <sha_linux_arm>
set -euo pipefail

if [ "$#" -ne 5 ]; then
  echo "usage: $0 <version> <sha_macos_arm> <sha_macos_intel> <sha_linux_intel> <sha_linux_arm>" >&2
  exit 2
fi

ver="$1"; sha_marm="$2"; sha_mintel="$3"; sha_lintel="$4"; sha_larm="$5"
out="$(cd "$(dirname "$0")/.." && pwd)/Formula/kin.rb"

# Unquoted heredoc: bash expands ${ver}/${sha_*} (our values) and leaves Ruby's
# #{version}/#{bin} literal (no leading $). There are no backticks or other $
# sequences in the formula, so nothing else is interpolated.
cat > "$out" <<RUBY
# SPDX-License-Identifier: Apache-2.0
# Copyright 2026 Firelock, LLC
#
# GENERATED by scripts/render-formula.sh — do not hand-edit. The version and
# sha256s are regenerated from each kin release by
# .github/workflows/update-formula.yml, so they can never drift from the
# published assets.
class Kin < Formula
  desc "Semantic system of record for software work"
  homepage "https://github.com/firelock-ai/kin"
  version "${ver}"
  license "Apache-2.0"

  on_macos do
    on_arm do
      url "https://github.com/firelock-ai/kin/releases/download/v#{version}/kin-macos-aarch64.tar.gz"
      sha256 "${sha_marm}"
    end
    on_intel do
      url "https://github.com/firelock-ai/kin/releases/download/v#{version}/kin-macos-x86_64.tar.gz"
      sha256 "${sha_mintel}"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/firelock-ai/kin/releases/download/v#{version}/kin-linux-x86_64.tar.gz"
      sha256 "${sha_lintel}"
    end
    on_arm do
      url "https://github.com/firelock-ai/kin/releases/download/v#{version}/kin-linux-aarch64.tar.gz"
      sha256 "${sha_larm}"
    end
  end

  def install
    # The release tarball expands to a single dir (e.g. kin-macos-aarch64/)
    # holding kin, kin-daemon, kin-vfs, and the VFS shim. Homebrew cd's into
    # that root on extract. kin-daemon is mandatory: kin init works without it,
    # but kin status / kin search / the MCP server all require it on PATH.
    bin.install "kin"
    bin.install "kin-daemon"
    bin.install "kin-vfs" if File.exist?("kin-vfs")
    lib.install "libkin_vfs_shim.dylib" if File.exist?("libkin_vfs_shim.dylib")
    lib.install "libkin_vfs_shim.so" if File.exist?("libkin_vfs_shim.so")
  end

  test do
    assert_match "kin", shell_output("#{bin}/kin --version")
  end
end
RUBY

echo "rendered ${out} for v${ver}"
